# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nestjs-postgres
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nestauth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
